EF-22-Template-Script (#23)
* feat(template.py): add template script
* fix(template.py): fix super-linter mypy error: Incompatible types in assignment
* docs(template.py): update README.rst; remove print statements from template.py
* docs(README.rst): update
* docs(index.rst): sync with README.rst
* fix(template.py): fix handling of docsrc/index.rst; add assets/template/index.rst
* fix(template.py): replace GITHUB_REPO_DESCRIPTION_SHORT before GITHUB_REPO_DESCRIPTION for README.rst and index.rst
* fix(CONTRIBUTING.md): add dots to email address so it matches assets/template/template_orig.yml
* fix(CODE_OF_CONDUCT.md): add email
* docs(CONTRIBUTING.md): improve
* fix(template.py): fix 'too many duplicates' super-linter error
* fix(various): fix super-linter warnings
* docs(various): improve
* 0.0.4